name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pytest -v --headed --browser chromium --alluredir=allure-results noon/tests

      - name: Upload Allure results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
